apiVersion: apps/v1
kind: Deployment
metadata:
  name: erlclu
  namespace: erlclu
spec:
  replicas: 5
  selector:
    matchLabels:
      app: erlclu
  template:
    metadata:
      labels:
        app: erlclu
    spec:
      serviceAccountName: erlclu
      initContainers:
        - name: erlclu-init
          image: docker.k3s.differentpla.net/erlclu-init:0.1.0
          imagePullPolicy: Always
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RELEASE_NODE
              value: erlclu
            - name: ISSUER_KIND
              value: ClusterIssuer
            - name: ISSUER_NAME
              value: k3s-ca-cluster-issuer
            - name: CERTS_DIR
              value: /certs
            - name: CERT_FILENAME
              value: tls-dist
          volumeMounts:
            - name: tls-dist
              mountPath: /certs
      containers:
        - name: erlclu
          image: docker.k3s.differentpla.net/erlclu:0.1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: RELEASE_COOKIE # might need to be RELX_COOKIE for some of the 'erlclu' script commands to work.
              valueFrom:
                secretKeyRef:
                  name: erlang-cookie
                  key: cookie
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: tls-dist
              mountPath: /certs
      volumes:
        - name: tls-dist
          emptyDir:
            medium: "Memory"
            sizeLimit: 32Ki
