apiVersion: apps/v1
kind: Deployment
metadata:
  name: erlclu
  namespace: erlclu
spec:
  replicas: 5
  selector:
    matchLabels:
      app: erlclu
  template:
    metadata:
      labels:
        app: erlclu
    spec:
      containers:
      - name: erlclu
        image: docker.k3s.differentpla.net/erlclu:0.1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: RELEASE_COOKIE # might need to be RELX_COOKIE for the remote_console to work.
          valueFrom:
            secretKeyRef:
              name: erlang-cookie
              key: cookie
