apiVersion: apps/v1
kind: Deployment
metadata:
  name: erlclu
  namespace: erlclu
spec:
  replicas: 5
  selector:
    matchLabels:
      app: erlclu
  template:
    metadata:
      labels:
        app: erlclu
    spec:
      serviceAccountName: erlclu
      initContainers:
        - name: erlclu-init
          image: docker.k3s.differentpla.net/erlclu-init:0.4.2
          imagePullPolicy: Always
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APPLICATION_LABEL
              value: erlclu
            - name: RELEASE_NODE
              value: erlclu
            - name: ISSUER_KIND
              value: Issuer
            - name: ISSUER_NAME
              value: erlclu-issuer
            - name: CERTS_DIR
              value: /certs
            - name: CERT_FILENAME
              value: tls-dist
          volumeMounts:
            - name: tls-dist
              mountPath: /certs
      containers:
        - name: erlclu
          image: docker.k3s.differentpla.net/erlclu:0.4.2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9153
          env:
            - name: RELEASE_COOKIE # might need to be RELX_COOKIE for some of the 'erlclu' script commands to work.
              valueFrom:
                secretKeyRef:
                  name: erlang-cookie
                  key: cookie
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SSH_SYSTEM_DIR
              value: /erlclu/ssh/system
            - name: SSH_USER_DIR
              value: /erlclu/ssh/user
          volumeMounts:
            - name: tls-dist
              mountPath: /certs
            - name: ssh-host-key
              mountPath: /erlclu/ssh/system
              readOnly: true
            - name: authorized-keys
              mountPath: /erlclu/ssh/user
      volumes:
        - name: tls-dist
          emptyDir:
            medium: "Memory"
            sizeLimit: 32Ki
        - name: ssh-host-key
          secret:
            secretName: ssh-host-key
        - name: authorized-keys
          configMap:
            name: authorized-keys-cm
            items:
            - key: authorized-keys
              path: authorized_keys
