apiVersion: apps/v1
kind: Deployment
metadata:
  name: erlclu
  namespace: erlclu
spec:
  replicas: 7
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: erlclu
  template:
    metadata:
      labels:
        app: erlclu
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
      serviceAccountName: erlclu
      initContainers:
        - name: erlclu-cert-init
          image: docker.k3s.differentpla.net/erlclu-cert-init:0.13.3
          imagePullPolicy: Always
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APPLICATION_LABEL
              value: erlclu
            - name: RELEASE_NODE
              value: erlclu
            - name: ISSUER_KIND
              value: Issuer
            - name: ISSUER_NAME
              value: erlclu-issuer
            - name: CERTS_DIR
              value: /certs/my
            - name: CERT_FILENAME
              value: tls-dist
          volumeMounts:
            - name: tls-dist
              mountPath: /certs/my
              readOnly: false
      containers:
        - name: erlclu
          image: docker.k3s.differentpla.net/erlclu:0.13.3
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "250m"
              memory: "96Mi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9153
          env:
            - name: RELEASE_COOKIE # might need to be RELX_COOKIE for some of the 'erlclu' script commands to work.
              valueFrom:
                secretKeyRef:
                  name: erlang-cookie
                  key: cookie
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONFIG_SOURCE
              value: /erlclu/_config
            - name: CONFIG_TARGET
              value: /erlclu/config
            - name: VMARGS_PATH
              value: /erlclu/config/vm.args
            - name: RELX_CONFIG_PATH
              value: /erlclu/config/sys.config
            - name: SSH_PORT
              value: "22"
            - name: SSH_SYSTEM_DIR
              value: /erlclu/ssh/system
            - name: SSH_USER_DIR
              value: /erlclu/ssh/user
          volumeMounts:
            - name: tls-dist
              mountPath: /certs/my
              readOnly: true
            - name: erlclu-ca-certificates
              mountPath: /certs/ca
            - name: ssh-host-key
              mountPath: /erlclu/ssh/system
              readOnly: true
            - name: authorized-keys
              mountPath: /erlclu/ssh/user
              readOnly: true
            - name: erlclu-config
              mountPath: /erlclu/_config
      volumes:
        - name: tls-dist
          emptyDir:
            medium: "Memory"
            sizeLimit: 32Ki
        - name: ssh-host-key
          secret:
            secretName: ssh-host-key
        - name: erlclu-ca-certificates
          secret:
            secretName: erlclu-ca-certificates
        - name: authorized-keys
          configMap:
            name: authorized-keys
            items:
            - key: authorized-keys
              path: authorized_keys
        - name: erlclu-config
          configMap:
            name: erlclu-config
