apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: request-certificate
  namespace: erlclu
  labels:
    app.kubernetes.io/instance: erlang-cluster
subjects:
- kind: ServiceAccount
  name: erlclu
roleRef:
  kind: Role
  name: certificate-requester
  apiGroup: rbac.authorization.k8s.io
