apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: erlclu
  namespace: erlclu
  labels:
    app.kubernetes.io/instance: erlang-cluster
spec:
  selector:
    matchLabels:
      app: erlclu
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
