apiVersion: v1
kind: ConfigMap
metadata:
  name: authorized-keys
  labels:
    app.kubernetes.io/instance: erlang-cluster
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  authorized-keys: |
