apiVersion: batch/v1
kind: CronJob
metadata:
  name: erlclu-request-cleanup
  namespace: erlclu
  labels:
    app.kubernetes.io/instance: erlang-cluster
spec:
  schedule: "8/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                          - amd64
                          - arm64
          containers:
            - name: request-cleanup
              image: docker.k3s.differentpla.net/erlclu-request-cleanup:0.16.0
              imagePullPolicy: Always
              env:
                - name: APPLICATION_LABEL
                  value: erlclu
                - name: MAX_AGE_MINS
                  value: "15"
          restartPolicy: Never
          activeDeadlineSeconds: 90
          serviceAccountName: erlclu
